#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 16, 2020 12:27:01 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m75" -background #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 700x645
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1370 729
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Image Manipulation"
    vTcl:DefineAlias "$top" "MainWindow" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #5d69d8 \
        -disabledforeground #ffffff \
        -font {-family {Proxima Nova Cn Bl} -size 28 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Image Manipulation Toolkit} 
    vTcl:DefineAlias "$top.lab55" "Label1" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $top.lab55
    frame $top.fra56 \
        -borderwidth 1 -background #e5e5e5 -height 125 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 675 
    vTcl:DefineAlias "$top.fra56" "Frame_one" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.fra56
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5d69d8 -command source_file -disabledforeground {} \
        -font {-family {Gill Sans MT} -size 10 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -takefocus 0 -text Select 
    vTcl:DefineAlias "$site_3_0.but57" "source_path_btn" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $site_3_0.but57
    entry $site_3_0.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief flat -selectbackground #c4c4c4 \
        -selectforeground black -takefocus 0 
    vTcl:DefineAlias "$site_3_0.ent58" "source_path" vTcl:WidgetProc "MainWindow" 1
    entry $site_3_0.ent43 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief flat -selectbackground #c4c4c4 \
        -selectforeground black -takefocus 0 
    vTcl:DefineAlias "$site_3_0.ent43" "Destination_path" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5d69d8 -command dest_file -disabledforeground {} \
        -font {-family {Gill Sans MT} -size 10 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -takefocus 0 -text Select 
    vTcl:DefineAlias "$site_3_0.but45" "dest_path_btn" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $site_3_0.but45
    label $site_3_0.lab59 \
        -activebackground #d3d3d3 -activeforeground black -anchor w \
        -background #e5e5e5 -disabledforeground #a3a3a3 \
        -font {-family {Proxima Nova Rg} -size 10 -weight bold} \
        -foreground #5d69d8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Select Image           :} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label2_10" vTcl:WidgetProc "MainWindow" 1
    label $site_3_0.lab60 \
        -activebackground #d3d3d3 -activeforeground black -anchor w \
        -background #e5e5e5 -disabledforeground #a3a3a3 \
        -font {-family {Proxima Nova Rg} -size 10 -weight bold} \
        -foreground #5d69d8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Output Destination  :} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label2_11" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.but57 \
        -in $site_3_0 -x 548 -y 19 -width 107 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 154 -y 20 -width 394 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent43 \
        -in $site_3_0 -x 153 -y 72 -width 394 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 547 -y 72 -width 107 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 10 -y 20 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 10 -y 70 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra56
    canvas $top.can65 \
        -background #e5e5e5 -borderwidth 2 -closeenough 1.0 -height 334 \
        -highlightbackground #e5e5e5 -highlightcolor black \
        -insertbackground black -insertontime 700 -selectbackground #c4c4c4 \
        -selectforeground black -takefocus 0 -width 440 
    vTcl:DefineAlias "$top.can65" "Canvas1" vTcl:WidgetProc "MainWindow" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Gill Sans MT} -size 21 -weight bold} \
        -foreground #5d69d8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Preview 
    vTcl:DefineAlias "$top.lab66" "Label2_3" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $top.lab66
    set site_3_0 $top.m75
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    frame $top.fra51 \
        -borderwidth 1 -background #e5e5e5 -height 335 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 225 
    vTcl:DefineAlias "$top.fra51" "apply_btn" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.fra51
    label $site_3_0.lab64 \
        -activebackground #d3d3d3 -activeforeground black -background #e5e5e5 \
        -disabledforeground #a3a3a3 \
        -font {-family {Proxima Nova Rg} -size 22 -weight bold} \
        -foreground #5d69d8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Select Effect} 
    vTcl:DefineAlias "$site_3_0.lab64" "Label2_9" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $site_3_0.lab64
    scale $site_3_0.sca46 \
        -activebackground #f9f9f9 -background #e5e5e5 -bigincrement 0.0 \
        -borderwidth 0 -command intensity_range \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -from 0.0 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -highlightthickness 0 -orient horizontal \
        -resolution 1.0 -sliderlength 20 -sliderrelief ridge \
        -tickinterval 0.0 -to 100.0 -troughcolor #fff 
    vTcl:DefineAlias "$site_3_0.sca46" "Intensity" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $site_3_0.sca46
    checkbutton $site_3_0.che49 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background #e5e5e5 -command horizontal_blurr_check \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Horizontal Blurr} -variable che50 
    vTcl:DefineAlias "$site_3_0.che49" "Horizontal_Blurr_Check" vTcl:WidgetProc "MainWindow" 1
    checkbutton $site_3_0.che50 \
        -activebackground #f8f8f8 -activeforeground #000000 \
        -background #e5e5e5 -command vertical_blurr_check \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Vertical Blurr} -variable che49 
    vTcl:DefineAlias "$site_3_0.che50" "Vertical_Blurr_Check" vTcl:WidgetProc "MainWindow" 1
    checkbutton $site_3_0.che53 \
        -activebackground #f8f8f8 -activeforeground #000000 \
        -background #e5e5e5 -command sharpness_check \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Sharpness -variable che51 
    vTcl:DefineAlias "$site_3_0.che53" "Sharpness_Check" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $site_3_0.che53
    label $site_3_0.lab55 \
        -activebackground #d3d3d3 -activeforeground black -background #e5e5e5 \
        -disabledforeground #a3a3a3 \
        -font {-family {Proxima Nova Rg} -size 14 -weight bold} \
        -foreground #5d69d8 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Intensity 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_7" vTcl:WidgetProc "MainWindow" 1
    vTcl:copy_lock $site_3_0.lab55
    radiobutton $site_3_0.rad45 \
        -activebackground #d9d9d9 -activeforeground #000000 \
        -background #e5e5e5 -command edge_detect -disabledforeground #d9d9d9 \
        -font {-family {Gill Sans MT} -size 10} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Edge Detect} -value 1 -variable radio 
    vTcl:DefineAlias "$site_3_0.rad45" "edge_detect_radio" vTcl:WidgetProc "MainWindow" 1
    radiobutton $site_3_0.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e5e5e5 -command face_detect -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Face Detect} -value 2 -variable radio 
    vTcl:DefineAlias "$site_3_0.rad47" "face_detect_radio" vTcl:WidgetProc "MainWindow" 1
    radiobutton $site_3_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e5e5e5 -command blurr_face -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -offrelief flat -text {Blurr Face} -value 3 \
        -variable radio 
    vTcl:DefineAlias "$site_3_0.rad48" "face_blurr" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5d69d8 -command save_btn -disabledforeground #a3a3a3 \
        -font {-family {Gill Sans MT} -size 10 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -text Save 
    vTcl:DefineAlias "$site_3_0.but45" "save_btn" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5d69d8 -command reset_btn -disabledforeground #a3a3a3 \
        -font {-family {Gill Sans MT} -size 10 -weight bold} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -text Reset 
    vTcl:DefineAlias "$site_3_0.but43" "reset_btn" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.lab64 \
        -in $site_3_0 -x 10 -y 10 -width 194 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.sca46 \
        -in $site_3_0 -x 10 -y 230 -width 190 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che49 \
        -in $site_3_0 -x 112 -y 55 -width 103 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che50 \
        -in $site_3_0 -x 6 -y 55 -width 90 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che53 \
        -in $site_3_0 -x 0 -y 91 -width 90 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 70 -y 203 -width 84 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 110 -y 87 -width 94 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 5 -y 124 -width 88 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 110 -y 125 -width 78 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 22 -y 283 -width 79 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 122 -y 282 -width 79 -height 30 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab55 \
        -in $top -x 0 -y -10 -width 704 -relwidth 0 -height 121 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra56 \
        -in $top -x 10 -y 120 -width 675 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can65 \
        -in $top -x 10 -y 300 -width 440 -relwidth 0 -height 334 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 250 -y 260 -width 214 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 462 -y 300 -width 225 -relwidth 0 -height 335 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}
proc intensity_range {args} { }

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

